sudo: false
language: ruby
rvm:
  - 2.5.0
  - 2.7.0
script:
  - bundle exec rspec spec
before_install: gem install bundler -v 2.1.4
deploy:
  provider: rubygems
  api_key:
    secure: your_secure_secret
  gem: lakatan
  on:
    tags: true
    repo: platanus/lakatan-gem
